parameters:
    ezpublish.persistence.solrdoc.search.content.criterion_visitor.match_all.class: xrow\EzPublishSolrDocsBundle\Persistence\Solrdoc\Content\Search\CriterionVisitor\MatchAll
    ezpublish.persistence.solrdoc.search.content.criterion_visitor.match_none.class: xrow\EzPublishSolrDocsBundle\Persistence\Solrdoc\Content\Search\CriterionVisitor\MatchNone
    ezpublish.persistence.solrdoc.search.content.criterion_visitor.content_id_in.class: xrow\EzPublishSolrDocsBundle\Persistence\Solrdoc\Content\Search\CriterionVisitor\ContentIdIn
    ezpublish.persistence.solrdoc.search.content.criterion_visitor.logical_and.class: xrow\EzPublishSolrDocsBundle\Persistence\Solrdoc\Content\Search\CriterionVisitor\LogicalAnd
    ezpublish.persistence.solrdoc.search.content.criterion_visitor.logical_or.class: xrow\EzPublishSolrDocsBundle\Persistence\Solrdoc\Content\Search\CriterionVisitor\LogicalOr
    ezpublish.persistence.solrdoc.search.content.criterion_visitor.logical_not.class: xrow\EzPublishSolrDocsBundle\Persistence\Solrdoc\Content\Search\CriterionVisitor\LogicalNot
    ezpublish.persistence.solrdoc.search.content.criterion_visitor.subtree_in.class: xrow\EzPublishSolrDocsBundle\Persistence\Solrdoc\Content\Search\CriterionVisitor\SubtreeIn
    ezpublish.persistence.solrdoc.search.content.criterion_visitor.content_type_id_in.class: xrow\EzPublishSolrDocsBundle\Persistence\Solrdoc\Content\Search\CriterionVisitor\ContentTypeIdIn
    ezpublish.persistence.solrdoc.search.content.criterion_visitor.content_type_identifier_in.class: xrow\EzPublishSolrDocsBundle\Persistence\Solrdoc\Content\Search\CriterionVisitor\ContentTypeIdentifierIn
    ezpublish.persistence.solrdoc.search.content.criterion_visitor.content_type_group_id_in.class: xrow\EzPublishSolrDocsBundle\Persistence\Solrdoc\Content\Search\CriterionVisitor\ContentTypeGroupIdIn
    ezpublish.persistence.solrdoc.search.content.criterion_visitor.location_id_in.class: xrow\EzPublishSolrDocsBundle\Persistence\Solrdoc\Content\Search\CriterionVisitor\LocationIdIn
    ezpublish.persistence.solrdoc.search.content.criterion_visitor.parent_location_id_in.class: xrow\EzPublishSolrDocsBundle\Persistence\Solrdoc\Content\Search\CriterionVisitor\ParentLocationIdIn
    ezpublish.persistence.solrdoc.search.content.criterion_visitor.section_in.class: xrow\EzPublishSolrDocsBundle\Persistence\Solrdoc\Content\Search\CriterionVisitor\SectionIn
    ezpublish.persistence.solrdoc.search.content.criterion_visitor.remote_id_in.class: xrow\EzPublishSolrDocsBundle\Persistence\Solrdoc\Content\Search\CriterionVisitor\RemoteIdIn
    ezpublish.persistence.solrdoc.search.content.criterion_visitor.language_code_in.class: xrow\EzPublishSolrDocsBundle\Persistence\Solrdoc\Content\Search\CriterionVisitor\LanguageCodeIn
    ezpublish.persistence.solrdoc.search.content.criterion_visitor.object_state_id_in.class: xrow\EzPublishSolrDocsBundle\Persistence\Solrdoc\Content\Search\CriterionVisitor\ObjectStateIdIn
    ezpublish.persistence.solrdoc.search.content.criterion_visitor.location_remote_id_in.class: xrow\EzPublishSolrDocsBundle\Persistence\Solrdoc\Content\Search\CriterionVisitor\LocationRemoteIdIn
    ezpublish.persistence.solrdoc.search.content.criterion_visitor.modified_in.class: xrow\EzPublishSolrDocsBundle\Persistence\Solrdoc\Content\Search\CriterionVisitor\DateMetadata\ModifiedIn
    ezpublish.persistence.solrdoc.search.content.criterion_visitor.published_in.class: xrow\EzPublishSolrDocsBundle\Persistence\Solrdoc\Content\Search\CriterionVisitor\DateMetadata\PublishedIn
    ezpublish.persistence.solrdoc.search.content.criterion_visitor.modified_between.class: xrow\EzPublishSolrDocsBundle\Persistence\Solrdoc\Content\Search\CriterionVisitor\DateMetadata\ModifiedBetween
    ezpublish.persistence.solrdoc.search.content.criterion_visitor.published_between.class: xrow\EzPublishSolrDocsBundle\Persistence\Solrdoc\Content\Search\CriterionVisitor\DateMetadata\PublishedBetween
    ezpublish.persistence.solrdoc.search.content.criterion_visitor.full_text.class: xrow\EzPublishSolrDocsBundle\Persistence\Solrdoc\Content\Search\CriterionVisitor\FullText
    ezpublish.persistence.solrdoc.search.content.criterion_visitor.user_metadata_in.class: xrow\EzPublishSolrDocsBundle\Persistence\Solrdoc\Content\Search\CriterionVisitor\UserMetadataIn
    ezpublish.persistence.solrdoc.search.content.criterion_visitor.map_location_distance_in.class: xrow\EzPublishSolrDocsBundle\Persistence\Solrdoc\Content\Search\CriterionVisitor\MapLocation\MapLocationDistanceIn
    ezpublish.persistence.solrdoc.search.content.criterion_visitor.map_location_distance_range.class: xrow\EzPublishSolrDocsBundle\Persistence\Solrdoc\Content\Search\CriterionVisitor\MapLocation\MapLocationDistanceRange
    ezpublish.persistence.solrdoc.search.content.criterion_visitor.field_in.class: xrow\EzPublishSolrDocsBundle\Persistence\Solrdoc\Content\Search\CriterionVisitor\Field\FieldIn
    ezpublish.persistence.solrdoc.search.content.criterion_visitor.field_range.class: xrow\EzPublishSolrDocsBundle\Persistence\Solrdoc\Content\Search\CriterionVisitor\Field\FieldRange
    ezpublish.persistence.solrdoc.search.content.criterion_visitor.visibility.class: xrow\EzPublishSolrDocsBundle\Persistence\Solrdoc\Content\Search\CriterionVisitor\Visibility
    ezpublish.persistence.solrdoc.search.content.criterion_visitor.custom_field.class: xrow\EzPublishSolrDocsBundle\Persistence\Solrdoc\Content\Search\CriterionVisitor\CustomField

services:
    ezpublish.persistence.solrdoc.search.content.criterion_visitor.match_all:
        class: %ezpublish.persistence.solrdoc.search.content.criterion_visitor.match_all.class%
        tags:
            - {name: ezpublish.persistence.solrdoc.search.content.criterion_visitor}

    ezpublish.persistence.solrdoc.search.content.criterion_visitor.match_none:
        class: %ezpublish.persistence.solrdoc.search.content.criterion_visitor.match_none.class%
        tags:
            - {name: ezpublish.persistence.solrdoc.search.content.criterion_visitor}

    ezpublish.persistence.solrdoc.search.content.criterion_visitor.content_id_in:
        class: %ezpublish.persistence.solrdoc.search.content.criterion_visitor.content_id_in.class%
        tags:
            - {name: ezpublish.persistence.solrdoc.search.content.criterion_visitor}

    ezpublish.persistence.solrdoc.search.content.criterion_visitor.logical_and:
        class: %ezpublish.persistence.solrdoc.search.content.criterion_visitor.logical_and.class%
        tags:
            - {name: ezpublish.persistence.solrdoc.search.content.criterion_visitor}

    ezpublish.persistence.solrdoc.search.content.criterion_visitor.logical_or:
        class: %ezpublish.persistence.solrdoc.search.content.criterion_visitor.logical_or.class%
        tags:
            - {name: ezpublish.persistence.solrdoc.search.content.criterion_visitor}

    ezpublish.persistence.solrdoc.search.content.criterion_visitor.logical_not:
        class: %ezpublish.persistence.solrdoc.search.content.criterion_visitor.logical_not.class%
        tags:
            - {name: ezpublish.persistence.solrdoc.search.content.criterion_visitor}

    ezpublish.persistence.solrdoc.search.content.criterion_visitor.subtree_in:
        class: %ezpublish.persistence.solrdoc.search.content.criterion_visitor.subtree_in.class%
        tags:
            - {name: ezpublish.persistence.solrdoc.search.content.criterion_visitor}

    ezpublish.persistence.solrdoc.search.content.criterion_visitor.content_type_id_in:
        class: %ezpublish.persistence.solrdoc.search.content.criterion_visitor.content_type_id_in.class%
        tags:
            - {name: ezpublish.persistence.solrdoc.search.content.criterion_visitor}

    # TODO: when Solr storage is enabled and multiple Solr storage engines are used simultaneously
    # 'ezpublish.spi.persistence.legacy.content_type.handler' dependency will need to be set through
    # alias or factory
    ezpublish.persistence.solrdoc.search.content.criterion_visitor.content_type_identifier_in:
        class: %ezpublish.persistence.solrdoc.search.content.criterion_visitor.content_type_identifier_in.class%
        arguments:
            - @ezpublish.spi.persistence.legacy.content_type.handler
        tags:
            - {name: ezpublish.persistence.solrdoc.search.content.criterion_visitor}

    ezpublish.persistence.solrdoc.search.content.criterion_visitor.content_type_group_id_in:
        class: %ezpublish.persistence.solrdoc.search.content.criterion_visitor.content_type_group_id_in.class%
        tags:
            - {name: ezpublish.persistence.solrdoc.search.content.criterion_visitor}

    ezpublish.persistence.solrdoc.search.content.criterion_visitor.location_id_in:
        class: %ezpublish.persistence.solrdoc.search.content.criterion_visitor.location_id_in.class%
        tags:
            - {name: ezpublish.persistence.solrdoc.search.content.criterion_visitor}

    ezpublish.persistence.solrdoc.search.content.criterion_visitor.parent_location_id_in:
        class: %ezpublish.persistence.solrdoc.search.content.criterion_visitor.parent_location_id_in.class%
        tags:
            - {name: ezpublish.persistence.solrdoc.search.content.criterion_visitor}

    ezpublish.persistence.solrdoc.search.content.criterion_visitor.section_in:
        class: %ezpublish.persistence.solrdoc.search.content.criterion_visitor.section_in.class%
        tags:
            - {name: ezpublish.persistence.solrdoc.search.content.criterion_visitor}

    ezpublish.persistence.solrdoc.search.content.criterion_visitor.remote_id_in:
        class: %ezpublish.persistence.solrdoc.search.content.criterion_visitor.remote_id_in.class%
        tags:
            - {name: ezpublish.persistence.solrdoc.search.content.criterion_visitor}

    ezpublish.persistence.solrdoc.search.content.criterion_visitor.language_code_in:
        class: %ezpublish.persistence.solrdoc.search.content.criterion_visitor.language_code_in.class%
        tags:
            - {name: ezpublish.persistence.solrdoc.search.content.criterion_visitor}

    ezpublish.persistence.solrdoc.search.content.criterion_visitor.object_state_id_in:
        class: %ezpublish.persistence.solrdoc.search.content.criterion_visitor.object_state_id_in.class%
        tags:
            - {name: ezpublish.persistence.solrdoc.search.content.criterion_visitor}

    ezpublish.persistence.solrdoc.search.content.criterion_visitor.location_remote_id_in:
        class: %ezpublish.persistence.solrdoc.search.content.criterion_visitor.location_remote_id_in.class%
        tags:
            - {name: ezpublish.persistence.solrdoc.search.content.criterion_visitor}

    ezpublish.persistence.solrdoc.search.content.criterion_visitor.modified_in:
        class: %ezpublish.persistence.solrdoc.search.content.criterion_visitor.modified_in.class%
        tags:
            - {name: ezpublish.persistence.solrdoc.search.content.criterion_visitor}

    ezpublish.persistence.solrdoc.search.content.criterion_visitor.published_in:
        class: %ezpublish.persistence.solrdoc.search.content.criterion_visitor.published_in.class%
        tags:
            - {name: ezpublish.persistence.solrdoc.search.content.criterion_visitor}

    ezpublish.persistence.solrdoc.search.content.criterion_visitor.modified_between:
        class: %ezpublish.persistence.solrdoc.search.content.criterion_visitor.modified_between.class%
        tags:
            - {name: ezpublish.persistence.solrdoc.search.content.criterion_visitor}

    ezpublish.persistence.solrdoc.search.content.criterion_visitor.published_between:
        class: %ezpublish.persistence.solrdoc.search.content.criterion_visitor.published_between.class%
        tags:
            - {name: ezpublish.persistence.solrdoc.search.content.criterion_visitor}

    ezpublish.persistence.solrdoc.search.content.criterion_visitor.full_text:
        class: %ezpublish.persistence.solrdoc.search.content.criterion_visitor.full_text.class%
        arguments:
            - @ezpublish.persistence.solrdoc.search.content.field_map
        tags:
            - {name: ezpublish.persistence.solrdoc.search.content.criterion_visitor}

    ezpublish.persistence.solrdoc.search.content.criterion_visitor.user_metadata_in:
        class: %ezpublish.persistence.solrdoc.search.content.criterion_visitor.user_metadata_in.class%
        tags:
            - {name: ezpublish.persistence.solrdoc.search.content.criterion_visitor}

    ezpublish.persistence.solrdoc.search.content.criterion_visitor.map_location_distance_in:
        class: %ezpublish.persistence.solrdoc.search.content.criterion_visitor.map_location_distance_in.class%
        arguments:
            - @ezpublish.persistence.solrdoc.search.content.field_map
        tags:
            - {name: ezpublish.persistence.solrdoc.search.content.criterion_visitor}

    ezpublish.persistence.solrdoc.search.content.criterion_visitor.map_location_distance_range:
        class: %ezpublish.persistence.solrdoc.search.content.criterion_visitor.map_location_distance_range.class%
        arguments:
            - @ezpublish.persistence.solrdoc.search.content.field_map
        tags:
            - {name: ezpublish.persistence.solrdoc.search.content.criterion_visitor}

    ezpublish.persistence.solrdoc.search.content.criterion_visitor.field_in:
        class: %ezpublish.persistence.solrdoc.search.content.criterion_visitor.field_in.class%
        arguments:
            - @ezpublish.persistence.solrdoc.search.content.field_map
        tags:
            - {name: ezpublish.persistence.solrdoc.search.content.criterion_visitor}

    ezpublish.persistence.solrdoc.search.content.criterion_visitor.field_range:
        class: %ezpublish.persistence.solrdoc.search.content.criterion_visitor.field_range.class%
        arguments:
            - @ezpublish.persistence.solrdoc.search.content.field_map
        tags:
            - {name: ezpublish.persistence.solrdoc.search.content.criterion_visitor}

    ezpublish.persistence.solrdoc.search.content.criterion_visitor.visibility:
        class: %ezpublish.persistence.solrdoc.search.content.criterion_visitor.visibility.class%
        tags:
            - {name: ezpublish.persistence.solrdoc.search.content.criterion_visitor}

    ezpublish.persistence.solrdoc.search.content.criterion_visitor.custom_field:
        class: %ezpublish.persistence.solrdoc.search.content.criterion_visitor.custom_field.class%
        tags:
            - {name: ezpublish.persistence.solrdoc.search.content.criterion_visitor}
