parameters:
    ezpublish.persistence.solrdoc.search.content.field_value_mapper.identifier.class: xrow\EzPublishSolrDocsBundle\Persistence\Solrdoc\Content\Search\FieldValueMapper\IdentifierMapper
    ezpublish.persistence.solrdoc.search.content.field_value_mapper.multiple_identifier.class: xrow\EzPublishSolrDocsBundle\Persistence\Solrdoc\Content\Search\FieldValueMapper\MultipleIdentifierMapper
    ezpublish.persistence.solrdoc.search.content.field_value_mapper.string.class: xrow\EzPublishSolrDocsBundle\Persistence\Solrdoc\Content\Search\FieldValueMapper\StringMapper
    ezpublish.persistence.solrdoc.search.content.field_value_mapper.multiple_string.class: xrow\EzPublishSolrDocsBundle\Persistence\Solrdoc\Content\Search\FieldValueMapper\MultipleStringMapper
    ezpublish.persistence.solrdoc.search.content.field_value_mapper.integer.class: xrow\EzPublishSolrDocsBundle\Persistence\Solrdoc\Content\Search\FieldValueMapper\IntegerMapper
    ezpublish.persistence.solrdoc.search.content.field_value_mapper.date.class: xrow\EzPublishSolrDocsBundle\Persistence\Solrdoc\Content\Search\FieldValueMapper\DateMapper
    ezpublish.persistence.solrdoc.search.content.field_value_mapper.price.class: xrow\EzPublishSolrDocsBundle\Persistence\Solrdoc\Content\Search\FieldValueMapper\PriceMapper
    ezpublish.persistence.solrdoc.search.content.field_value_mapper.boolean.class: xrow\EzPublishSolrDocsBundle\Persistence\Solrdoc\Content\Search\FieldValueMapper\BooleanMapper
    ezpublish.persistence.solrdoc.search.content.field_value_mapper.multiple_boolean.class: xrow\EzPublishSolrDocsBundle\Persistence\Solrdoc\Content\Search\FieldValueMapper\MultipleBooleanMapper
    ezpublish.persistence.solrdoc.search.content.field_value_mapper.geo_location.class: xrow\EzPublishSolrDocsBundle\Persistence\Solrdoc\Content\Search\FieldValueMapper\GeoLocationMapper

services:
    ezpublish.persistence.solrdoc.search.content.field_value_mapper.identifier:
        class: %ezpublish.persistence.solrdoc.search.content.field_value_mapper.identifier.class%
        tags:
            - {name: ezpublish.persistence.solrdoc.search.content.field_value_mapper}

    ezpublish.persistence.solrdoc.search.content.field_value_mapper.multiple_identifier:
        class: %ezpublish.persistence.solrdoc.search.content.field_value_mapper.multiple_identifier.class%
        tags:
            - {name: ezpublish.persistence.solrdoc.search.content.field_value_mapper}

    ezpublish.persistence.solrdoc.search.content.field_value_mapper.string:
        class: %ezpublish.persistence.solrdoc.search.content.field_value_mapper.string.class%
        tags:
            - {name: ezpublish.persistence.solrdoc.search.content.field_value_mapper}

    ezpublish.persistence.solrdoc.search.content.field_value_mapper.multiple_string:
        class: %ezpublish.persistence.solrdoc.search.content.field_value_mapper.multiple_string.class%
        tags:
            - {name: ezpublish.persistence.solrdoc.search.content.field_value_mapper}

    ezpublish.persistence.solrdoc.search.content.field_value_mapper.integer:
        class: %ezpublish.persistence.solrdoc.search.content.field_value_mapper.integer.class%
        tags:
            - {name: ezpublish.persistence.solrdoc.search.content.field_value_mapper}

    ezpublish.persistence.solrdoc.search.content.field_value_mapper.date:
        class: %ezpublish.persistence.solrdoc.search.content.field_value_mapper.date.class%
        tags:
            - {name: ezpublish.persistence.solrdoc.search.content.field_value_mapper}

    ezpublish.persistence.solrdoc.search.content.field_value_mapper.price:
        class: %ezpublish.persistence.solrdoc.search.content.field_value_mapper.price.class%
        tags:
            - {name: ezpublish.persistence.solrdoc.search.content.field_value_mapper}

    ezpublish.persistence.solrdoc.search.content.field_value_mapper.boolean:
        class: %ezpublish.persistence.solrdoc.search.content.field_value_mapper.boolean.class%
        tags:
            - {name: ezpublish.persistence.solrdoc.search.content.field_value_mapper}

    ezpublish.persistence.solrdoc.search.content.field_value_mapper.multiple_boolean:
        class: %ezpublish.persistence.solrdoc.search.content.field_value_mapper.multiple_boolean.class%
        tags:
            - {name: ezpublish.persistence.solrdoc.search.content.field_value_mapper}

    ezpublish.persistence.solrdoc.search.content.field_value_mapper.geo_location:
        class: %ezpublish.persistence.solrdoc.search.content.field_value_mapper.geo_location.class%
        tags:
            - {name: ezpublish.persistence.solrdoc.search.content.field_value_mapper}
