parameters:
    ezpublish.persistence.solrdoc.slot.class: eZ\Publish\Core\Persistence\Solr\Slot
    ezpublish.persistence.solrdoc.slot.publish_version.class: eZ\Publish\Core\Persistence\Solr\Slot\PublishVersion
    ezpublish.persistence.solrdoc.slot.copy_content.class: eZ\Publish\Core\Persistence\Solr\Slot\CopyContent
    ezpublish.persistence.solrdoc.slot.delete_content.class: eZ\Publish\Core\Persistence\Solr\Slot\DeleteContent
    ezpublish.persistence.solrdoc.slot.delete_version.class: eZ\Publish\Core\Persistence\Solr\Slot\DeleteVersion
    ezpublish.persistence.solrdoc.slot.delete_location.class: eZ\Publish\Core\Persistence\Solr\Slot\DeleteLocation
    ezpublish.persistence.solrdoc.slot.create_user.class: eZ\Publish\Core\Persistence\Solr\Slot\CreateUser
    ezpublish.persistence.solrdoc.slot.create_user_group.class: eZ\Publish\Core\Persistence\Solr\Slot\CreateUserGroup
    ezpublish.persistence.solrdoc.slot.move_user_group.class: eZ\Publish\Core\Persistence\Solr\Slot\MoveUserGroup
    ezpublish.persistence.solrdoc.slot.copy_subtree.class: eZ\Publish\Core\Persistence\Solr\Slot\CopySubtree
    ezpublish.persistence.solrdoc.slot.move_subtree.class: eZ\Publish\Core\Persistence\Solr\Slot\MoveSubtree
    ezpublish.persistence.solrdoc.slot.trash.class: eZ\Publish\Core\Persistence\Solr\Slot\Trash
    ezpublish.persistence.solrdoc.slot.recover.class: eZ\Publish\Core\Persistence\Solr\Slot\Recover
    ezpublish.persistence.solrdoc.slot.hide_location.class: eZ\Publish\Core\Persistence\Solr\Slot\HideLocation
    ezpublish.persistence.solrdoc.slot.unhide_location.class: eZ\Publish\Core\Persistence\Solr\Slot\UnhideLocation
    ezpublish.persistence.solrdoc.slot.set_content_state.class: eZ\Publish\Core\Persistence\Solr\Slot\SetContentState

services:
    ezpublish.persistence.solrdoc.slot:
        class: %ezpublish.persistence.solrdoc.slot.class%
        abstract: true
        arguments:
            - @ezpublish.api.inner_repository
            - @ezpublish.api.persistence_handler

    ezpublish.persistence.solrdoc.slot.publish_version:
        parent: ezpublish.persistence.solrdoc.slot
        class: %ezpublish.persistence.solrdoc.slot.publish_version.class%
        tags:
            - {name: ezpublish.persistence.solrdoc.slot, signal: ContentService\PublishVersionSignal}

    ezpublish.persistence.solrdoc.slot.copy_content:
        parent: ezpublish.persistence.solrdoc.slot
        class: %ezpublish.persistence.solrdoc.slot.copy_content.class%
        tags:
            - {name: ezpublish.persistence.solrdoc.slot, signal: ContentService\CopyContentSignal}

    ezpublish.persistence.solrdoc.slot.delete_content:
        parent: ezpublish.persistence.solrdoc.slot
        class: %ezpublish.persistence.solrdoc.slot.delete_content.class%
        tags:
            - {name: ezpublish.persistence.solrdoc.slot, signal: ContentService\DeleteContentSignal}

    ezpublish.persistence.solrdoc.slot.delete_version:
        parent: ezpublish.persistence.solrdoc.slot
        class: %ezpublish.persistence.solrdoc.slot.delete_version.class%
        tags:
            - {name: ezpublish.persistence.solrdoc.slot, signal: ContentService\DeleteVersionSignal}

    ezpublish.persistence.solrdoc.slot.delete_location:
        parent: ezpublish.persistence.solrdoc.slot
        class: %ezpublish.persistence.solrdoc.slot.delete_location.class%
        tags:
            - {name: ezpublish.persistence.solrdoc.slot, signal: LocationService\DeleteLocationSignal}

    ezpublish.persistence.solrdoc.slot.create_user:
        parent: ezpublish.persistence.solrdoc.slot
        class: %ezpublish.persistence.solrdoc.slot.create_user.class%
        tags:
            - {name: ezpublish.persistence.solrdoc.slot, signal: UserService\CreateUserSignal}

    ezpublish.persistence.solrdoc.slot.create_user_group:
        parent: ezpublish.persistence.solrdoc.slot
        class: %ezpublish.persistence.solrdoc.slot.create_user_group.class%
        tags:
            - {name: ezpublish.persistence.solrdoc.slot, signal: UserService\CreateUserGroupSignal}

    ezpublish.persistence.solrdoc.slot.move_user_group:
        parent: ezpublish.persistence.solrdoc.slot
        class: %ezpublish.persistence.solrdoc.slot.move_user_group.class%
        tags:
            - {name: ezpublish.persistence.solrdoc.slot, signal: UserService\MoveUserGroupSignal}

    ezpublish.persistence.solrdoc.slot.copy_subtree:
        parent: ezpublish.persistence.solrdoc.slot
        class: %ezpublish.persistence.solrdoc.slot.copy_subtree.class%
        tags:
            - {name: ezpublish.persistence.solrdoc.slot, signal: LocationService\CopySubtreeSignal}

    ezpublish.persistence.solrdoc.slot.move_subtree:
        parent: ezpublish.persistence.solrdoc.slot
        class: %ezpublish.persistence.solrdoc.slot.move_subtree.class%
        tags:
            - {name: ezpublish.persistence.solrdoc.slot, signal: LocationService\MoveSubtreeSignal}

    ezpublish.persistence.solrdoc.slot.trash:
        parent: ezpublish.persistence.solrdoc.slot
        class: %ezpublish.persistence.solrdoc.slot.trash.class%
        tags:
            - {name: ezpublish.persistence.solrdoc.slot, signal: TrashService\TrashSignal}

    ezpublish.persistence.solrdoc.slot.recover:
        parent: ezpublish.persistence.solrdoc.slot
        class: %ezpublish.persistence.solrdoc.slot.recover.class%
        tags:
            - {name: ezpublish.persistence.solrdoc.slot, signal: TrashService\RecoverSignal}

    ezpublish.persistence.solrdoc.slot.hide_location:
        parent: ezpublish.persistence.solrdoc.slot
        class: %ezpublish.persistence.solrdoc.slot.hide_location.class%
        tags:
            - {name: ezpublish.persistence.solrdoc.slot, signal: LocationService\HideLocationSignal}

    ezpublish.persistence.solrdoc.slot.unhide_location:
        parent: ezpublish.persistence.solrdoc.slot
        class: %ezpublish.persistence.solrdoc.slot.unhide_location.class%
        tags:
            - {name: ezpublish.persistence.solrdoc.slot, signal: LocationService\UnhideLocationSignal}

    ezpublish.persistence.solrdoc.slot.set_content_state:
        parent: ezpublish.persistence.solrdoc.slot
        class: %ezpublish.persistence.solrdoc.slot.set_content_state.class%
        tags:
            - {name: ezpublish.persistence.solrdoc.slot, signal: ObjectStateService\SetContentStateSignal}
