parameters:
    ezpublish.persistence.solrdoc.search.content.sort_clause_visitor.content_id.class: xrow\EzPublishSolrDocsBundle\Persistence\Solrdoc\Content\Search\SortClauseVisitor\ContentId
    ezpublish.persistence.solrdoc.search.content.sort_clause_visitor.content_name.class: xrow\EzPublishSolrDocsBundle\Persistence\Solrdoc\Content\Search\SortClauseVisitor\ContentName
    ezpublish.persistence.solrdoc.search.content.sort_clause_visitor.location_path_string.class: xrow\EzPublishSolrDocsBundle\Persistence\Solrdoc\Content\Search\SortClauseVisitor\LocationPathString
    ezpublish.persistence.solrdoc.search.content.sort_clause_visitor.location_depth.class: xrow\EzPublishSolrDocsBundle\Persistence\Solrdoc\Content\Search\SortClauseVisitor\LocationDepth
    ezpublish.persistence.solrdoc.search.content.sort_clause_visitor.location_priority.class: xrow\EzPublishSolrDocsBundle\Persistence\Solrdoc\Content\Search\SortClauseVisitor\LocationPriority
    ezpublish.persistence.solrdoc.search.content.sort_clause_visitor.section_identifier.class: xrow\EzPublishSolrDocsBundle\Persistence\Solrdoc\Content\Search\SortClauseVisitor\SectionIdentifier
    ezpublish.persistence.solrdoc.search.content.sort_clause_visitor.section_name.class: xrow\EzPublishSolrDocsBundle\Persistence\Solrdoc\Content\Search\SortClauseVisitor\SectionName
    ezpublish.persistence.solrdoc.search.content.sort_clause_visitor.date_published.class: xrow\EzPublishSolrDocsBundle\Persistence\Solrdoc\Content\Search\SortClauseVisitor\DatePublished
    ezpublish.persistence.solrdoc.search.content.sort_clause_visitor.map_location_distance.class: xrow\EzPublishSolrDocsBundle\Persistence\Solrdoc\Content\Search\SortClauseVisitor\MapLocationDistance

services:
    ezpublish.persistence.solrdoc.search.content.sort_clause_visitor.content_id:
        class: %ezpublish.persistence.solrdoc.search.content.sort_clause_visitor.content_id.class%
        tags:
            - {name: ezpublish.persistence.solrdoc.search.content.sort_clause_visitor}

    ezpublish.persistence.solrdoc.search.content.sort_clause_visitor.content_name:
        class: %ezpublish.persistence.solrdoc.search.content.sort_clause_visitor.content_name.class%
        tags:
            - {name: ezpublish.persistence.solrdoc.search.content.sort_clause_visitor}

    ezpublish.persistence.solrdoc.search.content.sort_clause_visitor.location_path_string:
        class: %ezpublish.persistence.solrdoc.search.content.sort_clause_visitor.location_path_string.class%
        tags:
            - {name: ezpublish.persistence.solrdoc.search.content.sort_clause_visitor}

    ezpublish.persistence.solrdoc.search.content.sort_clause_visitor.location_depth:
        class: %ezpublish.persistence.solrdoc.search.content.sort_clause_visitor.location_depth.class%
        tags:
            - {name: ezpublish.persistence.solrdoc.search.content.sort_clause_visitor}

    ezpublish.persistence.solrdoc.search.content.sort_clause_visitor.location_priority:
        class: %ezpublish.persistence.solrdoc.search.content.sort_clause_visitor.location_priority.class%
        tags:
            - {name: ezpublish.persistence.solrdoc.search.content.sort_clause_visitor}

    ezpublish.persistence.solrdoc.search.content.sort_clause_visitor.section_identifier:
        class: %ezpublish.persistence.solrdoc.search.content.sort_clause_visitor.section_identifier.class%
        tags:
            - {name: ezpublish.persistence.solrdoc.search.content.sort_clause_visitor}

    ezpublish.persistence.solrdoc.search.content.sort_clause_visitor.section_name:
        class: %ezpublish.persistence.solrdoc.search.content.sort_clause_visitor.section_name.class%
        tags:
            - {name: ezpublish.persistence.solrdoc.search.content.sort_clause_visitor}

    ezpublish.persistence.solrdoc.search.content.sort_clause_visitor.date_published:
        class: %ezpublish.persistence.solrdoc.search.content.sort_clause_visitor.date_published.class%
        tags:
            - {name: ezpublish.persistence.solrdoc.search.content.sort_clause_visitor}

    ezpublish.persistence.solrdoc.search.content.sort_clause_visitor.map_location_distance:
        class: %ezpublish.persistence.solrdoc.search.content.sort_clause_visitor.map_location_distance.class%
        arguments:
            - @ezpublish.persistence.solrdoc.search.content.field_map
        tags:
            - {name: ezpublish.persistence.solrdoc.search.content.sort_clause_visitor}
