# Depends on some of the 'legacy' storage handlers, see 'ezpublish.spi.persistence.legacy_solr'
# service definition below for details
imports:
    - {resource: legacy_solrdoc/solr_override/criterion_visitors.yml}
    - {resource: legacy_solrdoc/solr_override/facet_builder_visitors.yml}
    - {resource: legacy_solrdoc/solr_override/field_value_mappers.yml}
    - {resource: legacy_solrdoc/solr_override/services.yml}
    - {resource: legacy_solrdoc/solr_override/slots.yml}
    - {resource: legacy_solrdoc/solr_override/sort_clause_visitors.yml}

parameters:
    ezpublish.solr_server: http://localhost:8983/
    ezpublish.persistence.solrdoc.search.content.gateway.native.class: xrow\EzPublishSolrDocsBundle\Persistence\Solrdoc\Content\Search\Gateway\Native
    ezpublish.spi.persistence.solrdoc.search.handler.content.class: xrow\EzPublishSolrDocsBundle\Persistence\Solrdoc\Content\Search\Handler
    ezpublish.persistence.solrdoc.search.content.field_map.class: xrow\EzPublishSolrDocsBundle\Persistence\Solrdoc\Content\Search\FieldMap

services:
    ezpublish.persistence.legacy_solrdoc.search.content.gateway.native:
        class: %ezpublish.persistence.solrdoc.search.content.gateway.native.class%
        arguments:
            - @ezpublish.persistence.solrdoc.search.content.gateway.client.http.stream
            - @ezpublish.persistence.solrdoc.search.content.criterion_visitor.aggregate
            - @ezpublish.persistence.solrdoc.search.content.sort_clause_visitor.aggregate
            - @ezpublish.persistence.solrdoc.search.content.facet_builder_visitor.aggregate
            - @ezpublish.persistence.solrdoc.search.content.field_value_mapper.aggregate
            - @ezpublish.spi.persistence.legacy.content.handler
            - @ezpublish.persistence.solrdoc.search.content.field_name_generator

    ezpublish.persistence.legacy_solrdoc.search.content.gateway:
        alias: ezpublish.persistence.legacy_solrdoc.search.content.gateway.native

    ezpublish.persistence.legacy_solrdoc.search.content.field_map:
        class: %ezpublish.persistence.solrdoc.search.content.field_map.class%
        arguments:
            - @ezpublish.persistence.solrdoc.search.field_registry
            - @ezpublish.spi.persistence.legacy.content_type.handler
            - @ezpublish.persistence.solrdoc.search.content.field_name_generator

    # TODO: when Solr storage is enabled and multiple Solr storage engines are used simultaneously
    # this service will need to be set through factory, see https://jira.ez.no/browse/EZP-22846
    ezpublish.persistence.solrdoc.search.content.field_map:
        alias: ezpublish.persistence.legacy_solrdoc.search.content.field_map

    ezpublish.spi.persistence.legacy_solrdoc.search.handler.content:
        class: %ezpublish.spi.persistence.solrdoc.search.handler.content.class%
        arguments:
            - @ezpublish.persistence.legacy_solrdoc.search.content.gateway
            - @ezpublish.persistence.solrdoc.search.field_registry
            - @ezpublish.spi.persistence.legacy.location.handler
            - @ezpublish.spi.persistence.legacy.content_type.handler
            - @ezpublish.spi.persistence.legacy.object_state.handler
            - @ezpublish.spi.persistence.legacy.section.handler
            - @ezpublish.persistence.solrdoc.search.content.field_name_generator
        lazy: true

    ezpublish.spi.persistence.legacy_solrdoc:
        class: %ezpublish.spi.persistence.legacy.class%
        arguments:
            - @ezpublish.spi.persistence.legacy.content.handler
            - @ezpublish.spi.persistence.legacy_solrdoc.search.handler.content
            - @ezpublish.spi.persistence.legacy.content_type.handler
            - @ezpublish.spi.persistence.legacy.language.handler
            - @ezpublish.spi.persistence.legacy.location.handler
            - @ezpublish.spi.persistence.legacy.search.handler.location
            - @ezpublish.spi.persistence.legacy.object_state.handler
            - @ezpublish.spi.persistence.legacy.section.handler
            - @ezpublish.spi.persistence.legacy.transactionhandler
            - @ezpublish.spi.persistence.legacy.trash.handler
            - @ezpublish.spi.persistence.legacy.url_alias.handler
            - @ezpublish.spi.persistence.legacy.url_wildcard.handler
            - @ezpublish.spi.persistence.legacy.user.handler
        tags:
            - {name: ezpublish.storageEngine, alias: legacy_solrdoc}
        lazy: true
