parameters:
    xrow_ez_publish_solr_docs.solrserver:
      endpoint: 
        localhost:
          host: '127.0.0.1'
          port: 8983
          path: '/solr/ezp-default'
    xrow_ez_publish_solr_docs.solrglobalconfig:
      meta_installation_url_ms: "http://www.example.com/"
      meta_installation_id_ms: "6f700e7b8963e3abc508b9708f4529bc"
      meta_owner_name_t: "Administrator User"
      meta_owner_group_id_si: 13
      meta_object_states_si: 1
      meta_language_code_ms: "ger-DE"
    xrow_ez_publish_solr_docs.solr_classes:
        s_artikel:
            names:
                'ger-DE': "SolrArtikel"
            descriptions:
                'ger-DE': ""
            contentTypeGroups:
            id: 1000
            status: 0
            identifier: "s_artikel"
            creationDate: 1410248460
            modificationDate: 1410248460
            creatorId: 14
            modifierId: 14
            remoteId: 40faa822edc579b02c25f6bb7beec3ad
            urlAliasSchema: ""
            nameSchema: "<titel>"
            isContainer: true
            mainLanguageCode: "ger-DE"
            defaultAlwaysAvailable: true
            defaultSortField: 1
            defaultSortOrder: 1
            fields:
              titel:
                  id: 1
                  identifier: "titel"
                  fieldTypeIdentifier: "ezstring"
                  names:
                      'ger-DE': "Titel"
                  descriptions:
                      'ger-DE': "Titel"
                  fieldGroup : ""
                  position : 1
                  isTranslatable: false
                  isRequired: true
                  isInfoCollector: false
                  isSearchable: true
              veroeffentlichungsdatum:
                  id: 2
                  identifier: "veroeffentlichungsdatum"
                  fieldTypeIdentifier: "ezdatetime"
                  names:
                      'ger-DE': "Veröffentlichungsdatum"
                  descriptions:
                      'ger-DE': "Veröffentlichungsdatum"
                  fieldGroup : ""
                  position : 2
                  isTranslatable: false
                  isRequired: true
                  isInfoCollector: false
                  isSearchable: true
              vorspann:
                  id: 3
                  identifier: "vorspann"
                  fieldTypeIdentifier: "eztext"
                  names:
                      'ger-DE': "Vorspann"
                  descriptions:
                      'ger-DE': "Vorspann"
                  fieldGroup : ""
                  position : 3
                  isTranslatable: false
                  isRequired: true
                  isInfoCollector: false
                  isSearchable: true
              haupttext:
                  id: 4
                  identifier: "haupttext"
                  fieldTypeIdentifier: "eztext"
                  names:
                      'ger-DE': "Haupttext"
                  descriptions:
                      'ger-DE': "Haupttext"
                  fieldGroup : ""
                  position : 4
                  isTranslatable: false
                  isRequired: true
                  isInfoCollector: false
                  isSearchable: true
              schlagwoerter:
                  id: 5
                  identifier: "schlagwoerter"
                  fieldTypeIdentifier: "ezkeyword"
                  names:
                      'ger-DE': "Schlagwörter"
                  descriptions:
                      'ger-DE': "Schlagwörter"
                  fieldGroup : ""
                  position : 5
                  isTranslatable: false
                  isRequired: true
                  isInfoCollector: false
                  isSearchable: true
              rubriken:
                  id: 6
                  identifier: "rubriken"
                  fieldTypeIdentifier: "ezkeyword"
                  names:
                      'ger-DE': "Rubriken"
                  descriptions:
                      'ger-DE': "Rubriken"
                  fieldGroup : ""
                  position : 6
                  isTranslatable: false
                  isRequired: true
                  isInfoCollector: false
                  isSearchable: true
              url:
                  id: 7
                  identifier: "url"
                  fieldTypeIdentifier: "ezurl"
                  names:
                      'ger-DE': "URL"
                  descriptions:
                      'ger-DE': "URL"
                  fieldGroup : ""
                  position : 7
                  isTranslatable: false
                  isRequired: true
                  isInfoCollector: false
                  isSearchable: true
        solrtestdoc:
            names:
                'ger-DE': "SolrTestDoc"
            descriptions:
                'ger-DE': ""
            contentTypeGroups:
            id: 9900
            status: 0
            identifier: "solrtestdoc"
            creationDate: 1410248460
            modificationDate: 1410248460
            creatorId: 14
            modifierId: 14
            remoteId: 40faa822edc579b02c25f6bb7beec3ad
            urlAliasSchema: ""
            nameSchema: "<titel>"
            isContainer: true
            mainLanguageCode: "ger-DE"
            defaultAlwaysAvailable: true
            defaultSortField: 1
            defaultSortOrder: 1
            fields:
              ProductID:
                  id: 1
                  identifier: "ProductID"
                  fieldTypeIdentifier: "ezinteger"
                  names:
                      'ger-DE': "ProductID"
                  descriptions:
                      'ger-DE': "ProductID"
                  fieldGroup : ""
                  position : 1
                  isTranslatable: false
                  isRequired: true
                  isInfoCollector: false
                  isSearchable: true
              ProductName:
                  id: 2
                  identifier: "ProductName"
                  fieldTypeIdentifier: "ezstring"
                  names:
                      'ger-DE': "ProductName"
                  descriptions:
                      'ger-DE': "ProductName"
                  fieldGroup : ""
                  position : 2
                  isTranslatable: false
                  isRequired: true
                  isInfoCollector: false
                  isSearchable: true
              SupplierID:
                  id: 3
                  identifier: "SupplierID"
                  fieldTypeIdentifier: "ezinteger"
                  names:
                      'ger-DE': "SupplierID"
                  descriptions:
                      'ger-DE': "SupplierID"
                  fieldGroup : ""
                  position : 3
                  isTranslatable: false
                  isRequired: true
                  isInfoCollector: false
                  isSearchable: true
              CategoryID:
                  id: 4
                  identifier: "CategoryID"
                  fieldTypeIdentifier: "ezinteger"
                  names:
                      'ger-DE': "CategoryID"
                  descriptions:
                      'ger-DE': "CategoryID"
                  fieldGroup : ""
                  position : 4
                  isTranslatable: false
                  isRequired: true
                  isInfoCollector: false
                  isSearchable: true
              QuantityPerUnit:
                  id: 5
                  identifier: "QuantityPerUnit"
                  fieldTypeIdentifier: "ezstring"
                  names:
                      'ger-DE': "QuantityPerUnit"
                  descriptions:
                      'ger-DE': "QuantityPerUnit"
                  fieldGroup : ""
                  position : 5
                  isTranslatable: false
                  isRequired: true
                  isInfoCollector: false
                  isSearchable: true
              UnitPrice:
                  id: 6
                  identifier: "UnitPrice"
                  fieldTypeIdentifier: "ezfloat"
                  names:
                      'ger-DE': "UnitPrice"
                  descriptions:
                      'ger-DE': "UnitPrice"
                  fieldGroup : ""
                  position : 4
                  isTranslatable: false
                  isRequired: true
                  isInfoCollector: false
                  isSearchable: true
              UnitsInStock:
                  id: 7
                  identifier: "UnitsInStock"
                  fieldTypeIdentifier: "ezinteger"
                  names:
                      'ger-DE': "UnitsInStock"
                  descriptions:
                      'ger-DE': "UnitsInStock"
                  fieldGroup : ""
                  position : 7
                  isTranslatable: false
                  isRequired: true
                  isInfoCollector: false
                  isSearchable: true
              UnitsOnOrder:
                  id: 8
                  identifier: "UnitsOnOrder"
                  fieldTypeIdentifier: "ezinteger"
                  names:
                      'ger-DE': "UnitsOnOrder"
                  descriptions:
                      'ger-DE': "UnitsOnOrder"
                  fieldGroup : ""
                  position : 8
                  isTranslatable: false
                  isRequired: true
                  isInfoCollector: false
                  isSearchable: true
              ReorderLevel:
                  id: 9
                  identifier: "ReorderLevel"
                  fieldTypeIdentifier: "ezinteger"
                  names:
                      'ger-DE': "ReorderLevel"
                  descriptions:
                      'ger-DE': "ReorderLevel"
                  fieldGroup : ""
                  position : 9
                  isTranslatable: false
                  isRequired: true
                  isInfoCollector: false
                  isSearchable: true
              Discontinued:
                  id: 10
                  identifier: "Discontinued"
                  fieldTypeIdentifier: "ezboolean"
                  names:
                      'ger-DE': "Discontinued"
                  descriptions:
                      'ger-DE': "Discontinued"
                  fieldGroup : ""
                  position : 10
                  isTranslatable: false
                  isRequired: true
                  isInfoCollector: false
                  isSearchable: true
        odata4product:
            names:
                'ger-DE': "odata4product"
            descriptions:
                'ger-DE': ""
            contentTypeGroups:
            id: 31900
            status: 0
            identifier: "odata4product"
            creationDate: 1410248460
            modificationDate: 1410248460
            creatorId: 14
            modifierId: 14
            remoteId: 40faa822edc579b02c25f6bb7beec3ad
            urlAliasSchema: ""
            nameSchema: "<ID>"
            isContainer: true
            mainLanguageCode: "ger-DE"
            defaultAlwaysAvailable: true
            defaultSortField: 1
            defaultSortOrder: 1
            fields:
              ID:
                  id: 1
                  identifier: "ID"
                  fieldTypeIdentifier: "ezinteger"
                  names:
                      'ger-DE': "ID"
                  descriptions:
                      'ger-DE': "ID"
                  fieldGroup : ""
                  position : 1
                  isTranslatable: false
                  isRequired: true
                  isInfoCollector: false
                  isSearchable: true
              Name:
                  id: 2
                  identifier: "Name"
                  fieldTypeIdentifier: "ezstring"
                  names:
                      'ger-DE': "Name"
                  descriptions:
                      'ger-DE': "Name"
                  fieldGroup : ""
                  position : 2
                  isTranslatable: false
                  isRequired: true
                  isInfoCollector: false
                  isSearchable: true
              Description:
                  id: 3
                  identifier: "Description"
                  fieldTypeIdentifier: "ezstring"
                  names:
                      'ger-DE': "Description"
                  descriptions:
                      'ger-DE': "Description"
                  fieldGroup : ""
                  position : 3
                  isTranslatable: false
                  isRequired: true
                  isInfoCollector: false
                  isSearchable: true
              ReleaseDate:
                  id: 4
                  identifier: "ReleaseDate"
                  fieldTypeIdentifier: "ezdatetime"
                  names:
                      'ger-DE': "ReleaseDate"
                  descriptions:
                      'ger-DE': "ReleaseDate"
                  fieldGroup : ""
                  position : 4
                  isTranslatable: false
                  isRequired: true
                  isInfoCollector: false
                  isSearchable: true
              DiscontinuedDate:
                  id: 5
                  identifier: "DiscontinuedDate"
                  fieldTypeIdentifier: "ezdatetime"
                  names:
                      'ger-DE': "CategoryID"
                  descriptions:
                      'ger-DE': "CategoryID"
                  fieldGroup : ""
                  position : 5
                  isTranslatable: false
                  isRequired: false
                  isInfoCollector: false
                  isSearchable: true
              Rating:
                  id: 6
                  identifier: "Rating"
                  fieldTypeIdentifier: "ezinteger"
                  names:
                      'ger-DE': "Rating"
                  descriptions:
                      'ger-DE': "Rating"
                  fieldGroup : ""
                  position : 6
                  isTranslatable: false
                  isRequired: true
                  isInfoCollector: false
                  isSearchable: true
              Price:
                  id: 6
                  identifier: "Price"
                  fieldTypeIdentifier: "ezfloat"
                  names:
                      'ger-DE': "Price"
                  descriptions:
                      'ger-DE': "Price"
                  fieldGroup : ""
                  position : 6
                  isTranslatable: false
                  isRequired: true
                  isInfoCollector: false
                  isSearchable: true