parameters:
    ezpublish.spi.persistence.legacy_solrdoc.content.handler.class: xrow\EzPublishSolrDocsBundle\Persistence\Legacysolrdoc\Content\Handler
    ezpublish.persistence.legacy_solrdoc.content.query_builder.class: eZ\Publish\Core\Persistence\Legacy\Content\Gateway\DoctrineDatabase\QueryBuilder
    ezpublish.persistence.legacy_solrdoc.content.gateway.class: xrow\EzPublishSolrDocsBundle\Persistence\Legacysolrdoc\Content\Gateway\DoctrineDatabase
    ezpublish.persistence.legacy_solrdoc.content.gateway.exception_conversion.class: eZ\Publish\Core\Persistence\Legacy\Content\Gateway\ExceptionConversion
    ezpublish.persistence.legacy_solrdoc.content.mapper.class: xrow\EzPublishSolrDocsBundle\Persistence\Legacysolrdoc\Content\Mapper
    ezpublish.persistence.legacy_solrdoc.field_handler.class: xrow\EzPublishSolrDocsBundle\Persistence\Legacysolrdoc\Content\FieldHandler
    ezpublish.persistence.legacy_solrdoc.tree_handler.class: xrow\EzPublishSolrDocsBundle\Persistence\Legacysolrdoc\Content\TreeHandler

services:
    ezpublish.persistence.legacy_solrdoc.content.query_builder:
        class: %ezpublish.persistence.legacy_solrdoc.content.query_builder.class%
        arguments:
            - @ezpublish.api.storage_engine.legacy.dbhandler

    ezpublish.persistence.legacy_solrdoc.content.mapper:
        class: %ezpublish.persistence.legacy_solrdoc.content.mapper.class%
        arguments:
            - @ezpublish.persistence.legacy.field_value_converter.registry
            - @ezpublish.spi.persistence.legacy_solrdoc.language.handler

    ezpublish.persistence.legacy_solrdoc.content.gateway.inner:
        class: %ezpublish.persistence.legacy_solrdoc.content.gateway.class%
        arguments:
            - @ezpublish.api.storage_engine.legacy.dbhandler
            - @ezpublish.persistence.legacy_solrdoc.content.query_builder
            - @ezpublish.spi.persistence.legacy_solrdoc.language.handler
            - @ezpublish.persistence.legacy.language.mask_generator

    ezpublish.persistence.legacy_solrdoc.content.gateway.exception_conversion:
        class: %ezpublish.persistence.legacy_solrdoc.content.gateway.exception_conversion.class%
        arguments:
            - @ezpublish.persistence.legacy_solrdoc.content.gateway.inner

    # To disable exception conversion layer override this alias so that it points to inner gateway
    ezpublish.persistence.legacy_solrdoc.content.gateway:
        alias: ezpublish.persistence.legacy_solrdoc.content.gateway.exception_conversion
        #alias: ezpublish.persistence.legacy_solrdoc.content.gateway.inner

    ezpublish.persistence.legacy_solrdoc.field_handler:
        class: %ezpublish.persistence.legacy_solrdoc.field_handler.class%
        arguments:
            - @ezpublish.persistence.legacy_solrdoc.content.gateway
            - @ezpublish.persistence.legacy_solrdoc.content.mapper
            - @ezpublish.persistence.legacy_solrdoc.external_storage_handler
            - @ezpublish.spi.persistence.legacy_solrdoc.language.handler
            - @ezpublish.persistence.field_type_registry
        lazy: true

    ezpublish.persistence.legacy_solrdoc.tree_handler:
        class: %ezpublish.persistence.legacy_solrdoc.tree_handler.class%
        arguments:
            - @ezpublish.persistence.legacy_solrdoc.location.gateway
            - @ezpublish.persistence.legacy_solrdoc.location.mapper
            - @ezpublish.persistence.legacy_solrdoc.content.gateway
            - @ezpublish.persistence.legacy_solrdoc.content.mapper
            - @ezpublish.persistence.legacy_solrdoc.field_handler

    ezpublish.spi.persistence.legacy_solrdoc.content.handler:
        class: %ezpublish.spi.persistence.legacy_solrdoc.content.handler.class%
        arguments:
            - @ezpublish.persistence.legacy_solrdoc.content.gateway
            - @ezpublish.persistence.legacy_solrdoc.location.gateway
            - @ezpublish.persistence.legacy_solrdoc.content.mapper
            - @ezpublish.persistence.legacy_solrdoc.field_handler
            - @ezpublish_solrdoc.persistence.slug_converter
            - @ezpublish.persistence.legacy_solrdoc.url_alias.gateway
            - @ezpublish.spi.persistence.legacy_solrdoc.content_type.handler
            - @ezpublish.persistence.legacy_solrdoc.tree_handler
        lazy: false
