parameters:
    ezpublish.spi.persistence.legacy_solrdoc.content_type.handler.class: xrow\EzPublishSolrDocsBundle\Persistence\Legacysolrdoc\Content\Type\Handler
    ezpublish.spi.persistence.legacy_solrdoc.content_type.handler.caching.class: xrow\EzPublishSolrDocsBundle\Persistence\Legacysolrdoc\Content\Type\MemoryCachingHandler
    ezpublish.persistence.legacy_solrdoc.content_type.gateway.class: xrow\EzPublishSolrDocsBundle\Persistence\Legacysolrdoc\Content\Type\Gateway\DoctrineDatabase
    ezpublish.persistence.legacy_solrdoc.content_type.gateway.exception_conversion.class: xrow\EzPublishSolrDocsBundle\Persistence\Legacysolrdoc\Content\Type\Gateway\ExceptionConversion
    ezpublish.persistence.legacy_solrdoc.content_type.mapper.class: xrow\EzPublishSolrDocsBundle\Persistence\Legacysolrdoc\Content\Type\Mapper
    ezpublish.persistence.legacy_solrdoc.content_type.update_handler.base.class: xrow\EzPublishSolrDocsBundle\Persistence\Legacysolrdoc\Content\Type\Update\Handler
    ezpublish.persistence.legacy_solrdoc.content_type.update_handler.class: xrow\EzPublishSolrDocsBundle\Persistence\Legacysolrdoc\Content\Type\Update\Handler\DoctrineDatabase
    ezpublish.persistence.legacy_solrdoc.content_type.update_handler.deferred.class: xrow\EzPublishSolrDocsBundle\Persistence\Legacysolrdoc\Content\Type\Update\Handler\DeferredLegacy
    ezpublish.persistence.legacy_solrdoc.content_type.content_updater.class: xrow\EzPublishSolrDocsBundle\Persistence\Legacysolrdoc\Content\Type\ContentUpdater

services:
    ezpublish.persistence.legacy_solrdoc.content_type.gateway.inner:
        class: %ezpublish.persistence.legacy_solrdoc.content_type.gateway.class%
        arguments:
            - @ezpublish.api.storage_engine.legacy.dbhandler
            - @ezpublish.persistence.legacy.language.mask_generator

    ezpublish.persistence.legacy_solrdoc.content_type.gateway.exception_conversion:
        class: %ezpublish.persistence.legacy_solrdoc.content_type.gateway.exception_conversion.class%
        arguments:
            - @ezpublish.persistence.legacy_solrdoc.content_type.gateway.inner

    # To disable exception conversion layer override this alias so that it points to inner gateway
    ezpublish.persistence.legacy_solrdoc.content_type.gateway:
        alias: ezpublish.persistence.legacy_solrdoc.content_type.gateway.exception_conversion

    ezpublish.persistence.legacy_solrdoc.content_type.mapper:
        class: %ezpublish.persistence.legacy_solrdoc.content_type.mapper.class%
        arguments:
            - @ezpublish.persistence.legacy.field_value_converter.registry

    ezpublish.persistence.legacy_solrdoc.content_type.content_updater:
        class: %ezpublish.persistence.legacy_solrdoc.content_type.content_updater.class%
        arguments:
            - @ezpublish.spi.persistence.legacy_solrdoc.search.handler.content
            - @ezpublish.persistence.legacy_solrdoc.content.gateway
            - @ezpublish.persistence.legacy.field_value_converter.registry
            - @ezpublish.persistence.legacy.external_storage_handler

    ezpublish.persistence.legacy_solrdoc.content_type.update_handler.base:
        abstract: true
        class: %ezpublish.persistence.legacy_solrdoc.content_type.update_handler.base.class%

    ezpublish.persistence.legacy_solrdoc.content_type.update_handler.basic:
        parent: ezpublish.persistence.legacy_solrdoc.content_type.update_handler.base
        class: %ezpublish.persistence.legacy_solrdoc.content_type.update_handler.class%
        arguments:
            - @ezpublish.persistence.legacy_solrdoc.content_type.gateway
            - @ezpublish.persistence.legacy_solrdoc.content_type.content_updater

    # Note: if deferred ContentType update handler is required uncomment this service and override
    # 'ezpublish.persistence.legacy.content_type.update_handler' alias so that it points to it
    #
    #ezpublish.persistence.legacy.content_type.update_handler.deferred:
    #    parent: ezpublish.persistence.legacy.content_type.update_handler.base
    #    class: %ezpublish.persistence.legacy.content_type.update_handler.deferred.class%
    #    arguments:
    #        - @ezpublish.persistence.legacy.content_type.gateway

    ezpublish.persistence.legacy_solrdoc.content_type.update_handler:
        alias: ezpublish.persistence.legacy_solrdoc.content_type.update_handler.basic

    ezpublish.spi.persistence.legacy_solrdoc.content_type.handler.inner:
        class: %ezpublish.spi.persistence.legacy_solrdoc.content_type.handler.class%
        arguments:
            - @ezpublish.persistence.legacy_solrdoc.content_type.gateway
            - @ezpublish.persistence.legacy_solrdoc.content_type.mapper
            - @ezpublish.persistence.legacy_solrdoc.content_type.update_handler

    ezpublish.spi.persistence.legacy_solrdoc.content_type.handler.caching:
        class: %ezpublish.spi.persistence.legacy_solrdoc.content_type.handler.caching.class%
        arguments:
            - @ezpublish.spi.persistence.legacy_solrdoc.content_type.handler.inner

    ezpublish.spi.persistence.legacy_solrdoc.content_type.handler:
        alias: ezpublish.spi.persistence.legacy_solrdoc.content_type.handler.caching
        lazy: true