parameters:
    ezpublish.persistence.legacy_solrdoc.external_storage_handler.class: xrow\EzPublishSolrDocsBundle\Persistence\Legacysolrdoc\Content\StorageHandler

    

services:
    ezpublish.persistence.legacy_solrdoc.external_storage_handler:
        class: %ezpublish.persistence.legacy.external_storage_handler.class%
        arguments:
            - @ezpublish_solrdoc.persistence.external_storage_registry
            -
                identifier: "LegacyStorage"
                connection: @ezpublish.api.storage_engine.legacy.dbhandler