parameters:
    ezpublish.persistence.legacy_solrdoc.language.mask_generator.class: eZ\Publish\Core\Persistence\Legacy\Content\Language\MaskGenerator
    ezpublish.spi.persistence.legacy_solrdoc.language.handler.class: xrow\EzPublishSolrDocsBundle\Persistence\Legacysolrdoc\Content\Language\Handler
    ezpublish.spi.persistence.legacy_solrdoc.language.handler.caching.class: xrow\EzPublishSolrDocsBundle\Persistence\Legacysolrdoc\Content\Language\CachingHandler
    ezpublish.persistence.legacy_solrdoc.language.cache.class: xrow\EzPublishSolrDocsBundle\Persistence\Legacysolrdoc\Content\Language\Cache
    ezpublish.persistence.legacy_solrdoc.language.mapper.class: xrow\EzPublishSolrDocsBundle\Persistence\Legacysolrdoc\Content\Language\Mapper
    ezpublish.persistence.legacy_solrdoc.language.gateway.class: xrow\EzPublishSolrDocsBundle\Persistence\Legacysolrdoc\Content\Language\Gateway\DoctrineDatabase
    ezpublish.persistence.legacy_solrdoc.language.gateway.exception_conversion.class: xrow\EzPublishSolrDocsBundle\Persistence\Legacysolrdoc\Content\Language\Gateway\ExceptionConversion

services:
    ezpublish.persistence.legacy_solrdoc.language.gateway.inner:
        class: %ezpublish.persistence.legacy_solrdoc.language.gateway.class%
        arguments:
            - @ezpublish.api.storage_engine.legacy.dbhandler

    ezpublish.persistence.legacy_solrdoc.language.gateway.exception_conversion:
        class: %ezpublish.persistence.legacy_solrdoc.language.gateway.exception_conversion.class%
        arguments:
            - @ezpublish.persistence.legacy_solrdoc.language.gateway.inner

    # To disable exception conversion layer override this alias so that it points to inner gateway
    ezpublish.persistence.legacy_solrdoc.language.gateway:
        alias: ezpublish.persistence.legacy_solrdoc.language.gateway.exception_conversion

    ezpublish.persistence.legacy_solrdoc.language.mapper:
        class: %ezpublish.persistence.legacy_solrdoc.language.mapper.class%

    ezpublish.spi.persistence.legacy_solrdoc.language.handler.inner:
        class: %ezpublish.spi.persistence.legacy_solrdoc.language.handler.class%
        arguments:
            - @ezpublish.persistence.legacy_solrdoc.language.gateway
            - @ezpublish.persistence.legacy_solrdoc.language.mapper

    ezpublish.persistence.legacy_solrdoc.language.cache:
        class: %ezpublish.persistence.legacy_solrdoc.language.cache.class%

    ezpublish.spi.persistence.legacy_solrdoc.language.handler.caching:
        class: %ezpublish.spi.persistence.legacy_solrdoc.language.handler.caching.class%
        arguments:
            - @ezpublish.spi.persistence.legacy_solrdoc.language.handler.inner
            - @ezpublish.persistence.legacy_solrdoc.language.cache

    ezpublish.spi.persistence.legacy_solrdoc.language.handler:
        alias: ezpublish.spi.persistence.legacy_solrdoc.language.handler.caching
        lazy: true

    ezpublish.persistence.legacy_solrdoc.language.mask_generator:
        class: %ezpublish.persistence.legacy_solrdoc.language.mask_generator.class%
        arguments: [@ezpublish.spi.persistence.legacy_solrdoc.language.handler]