parameters:
    ezpublish.spi.persistence.legacy_solrdoc.location.handler.class: xrow\EzPublishSolrDocsBundle\Persistence\Legacysolrdoc\Content\Location\Handler
    ezpublish.persistence.legacy_solrdoc.location.gateway.class: xrow\EzPublishSolrDocsBundle\Persistence\Legacysolrdoc\Content\Location\Gateway\DoctrineDatabase
    ezpublish.persistence.legacy_solrdoc.location.gateway.exception_conversion.class: xrow\EzPublishSolrDocsBundle\Persistence\Legacysolrdoc\Content\Location\Gateway\ExceptionConversion
    ezpublish.persistence.legacy_solrdoc.location.mapper.class: xrow\EzPublishSolrDocsBundle\Persistence\Legacysolrdoc\Content\Location\Mapper

services:
    ezpublish.persistence.legacy_solrdoc.location.gateway.inner:
        class: %ezpublish.persistence.legacy_solrdoc.location.gateway.class%
        arguments:
            - @ezpublish.api.storage_engine.legacy.dbhandler

    ezpublish.persistence.legacy_solrdoc.location.gateway.exception_conversion:
        class: %ezpublish.persistence.legacy_solrdoc.location.gateway.exception_conversion.class%
        arguments:
            - @ezpublish.persistence.legacy_solrdoc.location.gateway.inner

    # To disable exception conversion layer override this alias so that it points to inner gateway
    ezpublish.persistence.legacy_solrdoc.location.gateway:
        alias: ezpublish.persistence.legacy_solrdoc.location.gateway.exception_conversion

    ezpublish.persistence.legacy_solrdoc.location.mapper:
        class: %ezpublish.persistence.legacy_solrdoc.location.mapper.class%

    ezpublish.spi.persistence.legacy_solrdoc.location.handler:
        class: %ezpublish.spi.persistence.legacy_solrdoc.location.handler.class%
        arguments:
            - @ezpublish.persistence.legacy_solrdoc.location.gateway
            - @ezpublish.persistence.legacy_solrdoc.location.mapper
            - @ezpublish.spi.persistence.legacy_solrdoc.content.handler
            - @ezpublish.spi.persistence.legacy_solrdoc.object_state.handler
            - @ezpublish.persistence.legacy_solrdoc.tree_handler
        lazy: false
