parameters:
    ezpublish.spi.persistence.legacy_solrdoc.object_state.handler.class: xrow\EzPublishSolrDocsBundle\Persistence\Legacysolrdoc\Content\ObjectState\Handler
    ezpublish.persistence.legacy_solrdoc.object_state.mapper.class: xrow\EzPublishSolrDocsBundle\Persistence\Legacysolrdoc\Content\ObjectState\Mapper
    ezpublish.persistence.legacy_solrdoc.object_state.gateway.class: xrow\EzPublishSolrDocsBundle\Persistence\Legacysolrdoc\Content\ObjectState\Gateway\DoctrineDatabase
    ezpublish.persistence.legacy_solrdoc.object_state.gateway.exception_conversion.class: xrow\EzPublishSolrDocsBundle\Persistence\Legacysolrdoc\Content\ObjectState\Gateway\ExceptionConversion
    

services:
    ezpublish.persistence.legacy_solrdoc.object_state.gateway.inner:
        class: %ezpublish.persistence.legacy_solrdoc.object_state.gateway.class%
        arguments:
            - @ezpublish.api.storage_engine.legacy.dbhandler
            - @ezpublish.persistence.legacy_solrdoc.language.mask_generator

    ezpublish.persistence.legacy_solrdoc.object_state.gateway.exception_conversion:
        class: %ezpublish.persistence.legacy_solrdoc.object_state.gateway.exception_conversion.class%
        arguments:
            - @ezpublish.persistence.legacy_solrdoc.object_state.gateway.inner

    # To disable exception conversion layer override this alias so that it points to inner gateway
    ezpublish.persistence.legacy_solrdoc.object_state.gateway:
        alias: ezpublish.persistence.legacy_solrdoc.object_state.gateway.exception_conversion

    ezpublish.persistence.legacy_solrdoc.object_state.mapper:
        class: %ezpublish.persistence.legacy_solrdoc.object_state.mapper.class%
        arguments:
            - @ezpublish.spi.persistence.legacy_solrdoc.language.handler

    ezpublish.spi.persistence.legacy_solrdoc.object_state.handler:
        class: %ezpublish.spi.persistence.legacy_solrdoc.object_state.handler.class%
        arguments:
            - @ezpublish.persistence.legacy_solrdoc.object_state.gateway
            - @ezpublish.persistence.legacy_solrdoc.object_state.mapper
        lazy: true
