parameters:
    ezpublish.spi.persistence.legacy_solrdoc.section.handler.class: eZ\Publish\Core\Persistence\Legacy\Content\Section\Handler
    ezpublish.persistence.legacy_solrdoc.section.gateway.class: eZ\Publish\Core\Persistence\Legacy\Content\Section\Gateway\DoctrineDatabase
    ezpublish.persistence.legacy_solrdoc.section.gateway.exception_conversion.class: eZ\Publish\Core\Persistence\Legacy\Content\Section\Gateway\ExceptionConversion

services:
    ezpublish.persistence.legacy_solrdoc.section.gateway.inner:
        class: %ezpublish.persistence.legacy_solrdoc.section.gateway.class%
        arguments:
            - @ezpublish.api.storage_engine.legacy.dbhandler

    ezpublish.persistence.legacy_solrdoc.section.gateway.exception_conversion:
        class: %ezpublish.persistence.legacy_solrdoc.section.gateway.exception_conversion.class%
        arguments:
            - @ezpublish.persistence.legacy_solrdoc.section.gateway.inner

    # To disable exception conversion layer override this alias so that it points to inner gateway
    ezpublish.persistence.legacy_solrdoc.section.gateway:
        alias: ezpublish.persistence.legacy_solrdoc.section.gateway.exception_conversion

    ezpublish.spi.persistence.legacy_solrdoc.section.handler:
        class: %ezpublish.spi.persistence.legacy_solrdoc.section.handler.class%
        arguments:
            - @ezpublish.persistence.legacy_solrdoc.section.gateway
        lazy: true
