parameters:
    ezpublish.spi.persistence.legacy_solrdoc.url_alias.handler.class: xrow\EzPublishSolrDocsBundle\Persistence\Legacysolrdoc\Content\UrlAlias\Handler
    ezpublish.persistence.legacy_solrdoc.url_alias.mapper.class: xrow\EzPublishSolrDocsBundle\Persistence\Legacysolrdoc\Content\UrlAlias\Mapper
    ezpublish.persistence.legacy_solrdoc.url_alias.gateway.class: xrow\EzPublishSolrDocsBundle\Persistence\Legacysolrdoc\Content\UrlAlias\Gateway\DoctrineDatabase
    ezpublish.persistence.legacy_solrdoc.url_alias.gateway.exception_conversion.class: xrow\EzPublishSolrDocsBundle\Persistence\Legacysolrdoc\Content\UrlAlias\Gateway\ExceptionConversion

services:
    ezpublish.persistence.legacy_solrdoc.url_alias.gateway.inner:
        class: %ezpublish.persistence.legacy_solrdoc.url_alias.gateway.class%
        arguments:
            - @ezpublish.api.storage_engine.legacy.dbhandler
            - @ezpublish.persistence.legacy_solrdoc.language.mask_generator

    ezpublish.persistence.legacy_solrdoc.url_alias.gateway.exception_conversion:
        class: %ezpublish.persistence.legacy_solrdoc.url_alias.gateway.exception_conversion.class%
        arguments:
            - @ezpublish.persistence.legacy_solrdoc.url_alias.gateway.inner

    # To disable exception conversion layer override this alias so that it points to inner gateway
    ezpublish.persistence.legacy_solrdoc.url_alias.gateway:
        alias: ezpublish.persistence.legacy_solrdoc.url_alias.gateway.exception_conversion

    ezpublish.persistence.legacy_solrdoc.url_alias.mapper:
        class: %ezpublish.persistence.legacy_solrdoc.url_alias.mapper.class%
        arguments:
            - @ezpublish.persistence.legacy_solrdoc.language.mask_generator

    ezpublish.spi.persistence.legacy_solrdoc.url_alias.handler:
        class: %ezpublish.spi.persistence.legacy_solrdoc.url_alias.handler.class%
        arguments:
            - @ezpublish.persistence.legacy_solrdoc.url_alias.gateway
            - @ezpublish.persistence.legacy_solrdoc.url_alias.mapper
            - @ezpublish.persistence.legacy_solrdoc.location.gateway
            - @ezpublish.spi.persistence.legacy_solrdoc.language.handler
            - @ezpublish_solrdoc.persistence.slug_converter
        lazy: true
