parameters:
    ezpublish.spi.persistence.legacy_solrdoc.user.handler.class: eZ\Publish\Core\Persistence\Legacy\User\Handler
    ezpublish.persistence.legacy_solrdoc.user.mapper.class: eZ\Publish\Core\Persistence\Legacy\User\Mapper
    ezpublish.persistence.legacy_solrdoc.user.gateway.class: eZ\Publish\Core\Persistence\Legacy\User\Gateway\DoctrineDatabase
    ezpublish.persistence.legacy_solrdoc.user.gateway.exception_conversion.class: eZ\Publish\Core\Persistence\Legacy\User\Gateway\ExceptionConversion
    ezpublish.persistence.legacy_solrdoc.role.gateway.class: eZ\Publish\Core\Persistence\Legacy\User\Role\Gateway\DoctrineDatabase
    ezpublish.persistence.legacy_solrdoc.role.gateway.exception_conversion.class: eZ\Publish\Core\Persistence\Legacy\User\Role\Gateway\ExceptionConversion
    ezpublish.persistence.legacy_solrdoc.role.limitation.handler.class: eZ\Publish\Core\Persistence\Legacy\User\Role\LimitationHandler
    ezpublish.persistence.legacy_solrdoc.role.limitation.handler.object_state.class: eZ\Publish\Core\Persistence\Legacy\User\Role\LimitationHandler\ObjectStateHandler
    ezpublish.persistence.legacy_solrdoc.role.limitation.converter.class: eZ\Publish\Core\Persistence\Legacy\User\Role\LimitationConverter

services:
    ezpublish.persistence.legacy_solrdoc.user.gateway.inner:
        class: %ezpublish.persistence.legacy_solrdoc.user.gateway.class%
        arguments:
            - @ezpublish.api.storage_engine.legacy.dbhandler

    ezpublish.persistence.legacy_solrdoc.user.gateway.exception_conversion:
        class: %ezpublish.persistence.legacy_solrdoc.user.gateway.exception_conversion.class%
        arguments:
            - @ezpublish.persistence.legacy_solrdoc.user.gateway.inner

    # To disable exception conversion layer override this alias so that it points to inner gateway
    ezpublish.persistence.legacy_solrdoc.user.gateway:
        alias: ezpublish.persistence.legacy_solrdoc.user.gateway.exception_conversion

    ezpublish.persistence.legacy_solrdoc.role.gateway.inner:
        class: %ezpublish.persistence.legacy_solrdoc.role.gateway.class%
        arguments:
            - @ezpublish.api.storage_engine.legacy.dbhandler

    ezpublish.persistence.legacy_solrdoc.role.gateway.exception_conversion:
        class: %ezpublish.persistence.legacy_solrdoc.role.gateway.exception_conversion.class%
        arguments:
            - @ezpublish.persistence.legacy_solrdoc.role.gateway.inner

    # To disable exception conversion layer override this alias so that it points to inner gateway
    ezpublish.persistence.legacy_solrdoc.role.gateway:
        alias: ezpublish.persistence.legacy_solrdoc.role.gateway.exception_conversion

    ezpublish.persistence.legacy_solrdoc.user.mapper:
        class: %ezpublish.persistence.legacy_solrdoc.user.mapper.class%

    ezpublish.persistence.legacy_solrdoc.role.limitation.handler:
        abstract: true
        class: %ezpublish.persistence.legacy_solrdoc.role.limitation.handler.class%
        arguments:
            - @ezpublish.api.storage_engine.legacy.dbhandler

    ezpublish.persistence.legacy_solrdoc.role.limitation.handler.object_state:
        parent: ezpublish.persistence.legacy_solrdoc.role.limitation.handler
        class: %ezpublish.persistence.legacy_solrdoc.role.limitation.handler.object_state.class%
        tags:
            - {name: ezpublish.persistence.legacy_solrdoc.role.limitation.handler}

    # Note: services tagged with 'ezpublish.persistence.legacy.role.limitation.handler'
    # are registered to this one using compilation pass
    ezpublish.persistence.legacy_solrdoc.role.limitation.converter:
        class: %ezpublish.persistence.legacy_solrdoc.role.limitation.converter.class%

    ezpublish.spi.persistence.legacy_solrdoc.user.handler:
        class: %ezpublish.spi.persistence.legacy_solrdoc.user.handler.class%
        arguments:
            - @ezpublish.persistence.legacy_solrdoc.user.gateway
            - @ezpublish.persistence.legacy_solrdoc.role.gateway
            - @ezpublish.persistence.legacy_solrdoc.user.mapper
            - @ezpublish.persistence.legacy_solrdoc.role.limitation.converter
        lazy: true
